### PR TITLE
Remove `bin` to prevent overwriting others

### PR DESCRIPTION
**Pull request by huan**
See: https://github.com/SamVerschueren/tsd/issues/122

### CODE REVIEW

**Comment by voxpelli** [comment]
Should perhaps add a mention in the `README` that this package is a fork meant purely for programmatic usage, but I'm a big 👍 on this one

**Comment by christian-bromann** [comment]
This would also fix #2, big 👍  from my side too!

**Comment by SamVerschueren** [comment]
Fixed in 496cdda4c4562283f0205e7308db1f70ec771ec9 because had to do a small doc update as well.

Sorry about the delay and about the fact this caused projects to fail :(. The initial idea was for people to only install `@tsd/typescript` instead of both `typescript` and `@tsd/typescript`. Because both versions are identical so theoretically, you only need one. But turns out this is probably harder because tools rely on `typescript` or it is being installed somewhere as transient dependency.

Just checking, but is it ok if this is just fixed in the next `@tsd/typescript` release? If not, I can see if I can release a patch for every minor up until v4.0 or something.

**Comment by voxpelli** [comment]
@SamVerschueren No worries!

Maybe you can check what eg xo relies on and/or which versions of this module which are downloaded the most and release a few select patches if that doesn’t become too complex? Else I think it’s fine to keep it in only upcoming ones :)

**Pull request closed without merging**
